Web.UI/Models/Categorys.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Web.UI.Models
{
    public class Categorys
    {
        public int CategoryId { get; set; }

        [Required(ErrorMessage = "Category Name is required.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Category Description is required.")]
        public string Description { get; set; }
    }
}

Web.UI/Models/JsonResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.UI.Models
{
    public class JsonResponse
    {
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
        public string Description { get; set; }
        public object Data { get; set; }
        public int ErrorCode { get; set; }
        public List<string> Errors { get; set; }
    }
}

Web.UI/Controllers/CategorysController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Web.UI.Models;

namespace Web.UI.Controllers
{
    public class CategorysController : Controller
    {
        private string baseApiURL ="http://localhost:60868/api/Categorys";
        public async Task<IActionResult> Index()
        {
            var obj = await Insert(new Categorys() { Name = "Snacks", Description = "Snacks Desc"});
            return View();
        }

        public List<Categorys> GetCategorys()
        {
            List<Categorys> list = new List<Categorys>();
            return list;
        }

        public  async Task<Categorys> GetById(int id)
        {
            var category = new Categorys();

            using (HttpClient client = new HttpClient())
            {
                string endPoint = $"{baseApiURL}/getById/{id}";  //localhost.com/api/Categorys/getById/3

                using (var response =await client.GetAsync(endPoint))
                {
                    string resultStr = response.Content.ReadAsStringAsync().Result.ToString();
                    var jsonResponse = JsonConvert.DeserializeObject<JsonResponse>(resultStr); //Deserialize Result

                    if (jsonResponse.IsSuccess)
                    {
                        category = JsonConvert.DeserializeObject<Categorys>(jsonResponse.Data.ToString());
                    }
                    else
                    {

                    }
                }

             }

            return category;
        }

        public async Task<IActionResult> Insert(Categorys model)
        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = $"{baseApiURL}";
                StringContent content = new StringContent(JsonConvert.SerializeObject(model), 
                                                                                         Encoding.UTF8, "application/json");


                using (var response = await client.PostAsync(endPoint, content))
                {
                    string resultStr = response.Content.ReadAsStringAsync().Result.ToString();
                    var jsonResponse = JsonConvert.DeserializeObject<JsonResponse>(resultStr); //Deserialize Result
                }
            }
            return View();
        }
    }
}

Web.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.UI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web.UI/Views/Home/Index.cshtml
@{ 
    Layout = "/~Views/Shared/_Layout.cshtml ";
}

<h4>Home Page.</h4>

Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Web.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Categorys" asp-action="Index">Categorys</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Web.UI - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>